# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "mOQAu0F+F7YtoUZFs0fz/xYb7tCJmwM8vvZUpJ7927s5xK+cXT08W8jOybMnOoQ4vPrAUOtG/5PjegwK/u8v5O5bsMuW5svQZyxk4P+7dAcgtg48F5/kxwWB5A7WXdeHY2tOBjClnh29N5iB70hv65ognJCJyZYmMtNcCtdlglYqPTsbVnJuDI9F+pzZRRB+yJ+Y+ZO9s+I+HN09Y7CUs4+2Be9ug1h9Jt9esnXHTDtm1QO9GkHMrQbGJ93clHmnFhv6ikf/xIbJOTP3jY34W5uW1VMezupUCbgL+jFg+OUkBRfnxx8wl3CmACMaNPAwIk0qzqwFLHjQJAppezU98bTYxTCbjC2yuum5H0k6428uvo33fh8PJDoH0UV77aQlO1kTZA47HI3og6aJCR9kbOMTfWUFK0SjcJ6mtLMrVY6vA0lG/L4L0jj4+1GUqRCxeM0oIQIzDpuh7RwNxtVfQBHplUeMSqNkHoXb4kB6MMYO2UKtfBtU+HbFjSeim9UOXe+dcNMt+NeSzp+hU2jykS1VB9DWA7lbrCKYsipMEjkRoLZm1j/4+zK4C+U9Wh8ZP7PkvpDO7peEEym6YigLFUFwYlU9UJfYkpLrpKGYSegYd5gR6BUzAsdsrvh1x7IDce2r+mJxc5K7xkkDGxJK4eZuUUfzlD71vsxgBL6Z1TM="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
