travis:
  secure:
    BINSTAR_TOKEN: eIs4OrqZOkfGFvdAAf0kwx+zIPKVW5U60OtoRE5zlie97+JGyjIe/LLriPm7CDR2UczLGh1wKlqnG2HM9LPB6GilA2VjcwZxOUn5cT3XcHGHGi/f3j5pqzC40CSZG7Qp7M5A+GQeoQB7tUA4YNnb2K+6rt3ORFHbuXlcdnM6wwe5+1VjBUZYTiBLnFONTdUYlmsWBHhIcAO3aPz4fMcvn9tXtYCwFt2FFXyEr5O5EfhbGulLFQpUfi2wmU4gEITyBtZkE77BehoApQdnnEbbd9jA09HLJyZbIBno0Yk6GE55U1GzQL4AT0F7N1WjQdHqLSdYOOdZiZEtnKbGaENrSsIyc09yb18XjUG4a/DxjW9Hs/MiFkwWUQajttsMPgbSShLyuGbstBjtr72VA6aIiKVKwTo51KR4SGK0f0WDC9KDfIuRBMTtCxJ6kETG5RfZOBYjFLpeiGJeCrTzkuHHuFfaY6P6dE+wf5LiWU64SdOLimU5MY7OuL760ZYKV5zgW7jX3XpSBrRnyrtSZC6F9zVSEFaBsnzFJmWoO3ihOEyOBSsZKs4zl3FpDae6B1qUkgKOxkjO54uAb8XyUItBGToIlf04TA3RyrDftjTIabw5wEfNUjU/X7b/cnNv3zosOvdY0Fc8HUmQhG6Uc6cZelE4gcaBrV7Srlb73XWMeX4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
