travis:
  secure:
    BINSTAR_TOKEN: mOQAu0F+F7YtoUZFs0fz/xYb7tCJmwM8vvZUpJ7927s5xK+cXT08W8jOybMnOoQ4vPrAUOtG/5PjegwK/u8v5O5bsMuW5svQZyxk4P+7dAcgtg48F5/kxwWB5A7WXdeHY2tOBjClnh29N5iB70hv65ognJCJyZYmMtNcCtdlglYqPTsbVnJuDI9F+pzZRRB+yJ+Y+ZO9s+I+HN09Y7CUs4+2Be9ug1h9Jt9esnXHTDtm1QO9GkHMrQbGJ93clHmnFhv6ikf/xIbJOTP3jY34W5uW1VMezupUCbgL+jFg+OUkBRfnxx8wl3CmACMaNPAwIk0qzqwFLHjQJAppezU98bTYxTCbjC2yuum5H0k6428uvo33fh8PJDoH0UV77aQlO1kTZA47HI3og6aJCR9kbOMTfWUFK0SjcJ6mtLMrVY6vA0lG/L4L0jj4+1GUqRCxeM0oIQIzDpuh7RwNxtVfQBHplUeMSqNkHoXb4kB6MMYO2UKtfBtU+HbFjSeim9UOXe+dcNMt+NeSzp+hU2jykS1VB9DWA7lbrCKYsipMEjkRoLZm1j/4+zK4C+U9Wh8ZP7PkvpDO7peEEym6YigLFUFwYlU9UJfYkpLrpKGYSegYd5gR6BUzAsdsrvh1x7IDce2r+mJxc5K7xkkDGxJK4eZuUUfzlD71vsxgBL6Z1TM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
